# config.yaml
defaults:
  - model: lstm
  - training: train
  - dataset: dataloader
  - _self_


model:
  name: lstm
  input_dim: 2
  hidden_dims: 64
  num_layers: 4
  dropout: 0.6
  bidirectional: True
  use_layernorm: True

training:
  batch_size: 2
  learning_rate: 0.0001
  epochs: 100
  optimizer: adam
  seed: 3407
  device: cuda
  num_workers: 4
  display_step: 1000
  patience: 10


dataset:
  predictor_path: /app/dev/Seasonal_Climate/onedrive/cy_bench_8daybins_wheat_US.csv
  yield_path: /app/dev/Seasonal_Climate/cybench/cybench-data/wheat/US/yield_wheat_US.csv
  feature_selector: null  # e.g. ['tvag', 'drainage_class']
  max_timesteps: 46
  temporal_truncation: null  # e.g. [11, 15] to represent start/end index of time series
  train_years: [2017, 2018]
  proportion: 100
  state_selector: ['US-08', 'US-20', 'US-31', 'US-40', 'US-46', 'US-48']  # activate for USA
  # state_selector: ['BR41' 'BR42' 'BR43']  # activate for Brazil
  aez_selector: null
  results_path: /app/dev/Seasonal_Climate/results/lstm_us
